### ISSUE TITLE
unclear rate parameter

### ISSUE THREAD

**Issue by matkoniecz** [beeminder/apidocs#11]
http://api.beeminder.com/#attributes-2

>  "rate (number): The slope of the (final section of the) yellow brick road."

Is it a rate per day? Especially in context of http://api.beeminder.com/#creategoal it seems weird, compared to UI where you have both number and "per day/week/...".

Is `rate` supposed to be converted to a per day value?

`ruby --version
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]`
`ruby2.6 --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-gnu]`
Firefox 70.0.1 (64-bit)

https://github.com/beeminder/apidocs/commits/dev - dev branch appears to be outdated, so I skipped "This issue appears in the latest `dev` branch".

If this is an bug report, not a question, make sure to:

- [x] I'm not running Windows (which is unsupported), or if I am, I can confirm this issue appears on another platform, or Vagrant.
- [ ] This issue appears in the latest `dev` branch.
- [x] I've included my browser and Ruby version in this issue.

**Comment by bsoule** [comment]
closed by https://github.com/beeminder/apidocs/commit/21043a2594af44c75c65bb80924f1a26218accae & https://github.com/beeminder/apidocs/commit/7e5253bf476e426b8eec7f44c9041bce032ebe24
