### ISSUE TITLE
Use the font Stripe uses

### ISSUE THREAD

**Issue by dreeves** [beeminder/apidocs#2]

**Comment by bsoule** [comment]
There are loooots of nice sans-serif web fonts that are nice and free. This font, Whitney SSM, best I can tell, costs $99/month to use? 

https://www.typography.com/fonts/whitney/styles/whitneybasic

Actually, I'm a little vague on how fonts work on the internet. I found at least one place where I can maybe download the .ttf for free, but it looks like the fonts we're using come in .otf files, so anyway, research. Or just picking a nice, free font. Or letting a designer worry about it. That was majority of the niceness of this slate business. It's pre-designed.

**Comment by bsoule** [comment]
free web fonts:
https://fonts.google.com/?category=Sans+Serif,Display
https://edgewebfonts.adobe.com/fonts#/?class=sans-serif&recommendedFor=paragraphs
