### ISSUE TITLE
(Possibly) inaccurate "returns" for when creating multiple datapoints

### ISSUE THREAD

**Issue by jahkeup** [beeminder/apidocs#9]
When a client POSTs datapoints to the API (using `https://www.beeminder.com/api/v1/users/me/goals/SLUG/datapoints/create_all.json`), the response appears to be an array of the created datapoints which were submitted. This was surprising as the documentation suggests this would have been "the last created datapoint" rather than what actually is, what is - IMO - an intuitive response with all of the involved datapoints.

https://github.com/beeminder/apidocs/blob/9f4a69041f60d4ec43b8214904499adb0b6b1b23/source/index.html.md#L984-L986

Which shape is expected to be returned?

P.S. I'm combing through these pages while working on an API client, happy to drop issues as they crop up or open a pull request if that's preferred!

**Comment by dreeves** [comment]
PRs would be amazing! Thank you so much!

**Comment by bsoule** [comment]
closed in commit https://github.com/beeminder/apidocs/commit/e3c4cac6133b9d2e53e003b06a847c508d86c8a9
